#! /bin/env python3
"""Only compatible with ppm generated by GIMP!"""

map_ppm_path = "map.ppm"

map_output_path = "map"

def calculate_height(r, g, b):
    avg = (r+g+b)/3
    return int(avg / 255 * 9 + 0)

x = 0
y = 0
hs = []

with open(map_ppm_path) as f:
    f.readline()
    f.readline()
    xy = f.readline().strip().split(" ")
    x = int(xy[0])
    y = int(xy[1])
    f.readline()
    for _ in range(x):
        for _ in range(y):
            r = int(f.readline().strip())
            g = int(f.readline().strip())
            b = int(f.readline().strip())
            h = calculate_height(r, g, b)
            hs.append(h)

with open(map_output_path, "w") as map_file:
    for i in range(x):
        for j in range(y):
            h = hs[i * y + j]
            for _z in range(h):
                _x = j
                _y = x - i - 1
                if (_z < h-1):
                    map_file.write("dirt ")
                else:
                    map_file.write("grass ")
                map_file.write("%s %s %s\n" % (
                    _x - int(x/2),
                    _y - int(y/2),
                    _z,
                ))
