#! /bin/env python3
"""Only compatible with ppm generated by GIMP!"""

map_ppm_path = "map.ppm"

map_output_path = "map"

grass_block_id = 1
dirt_block_id  = 2
stone_block_id = 3
grass_id       = 4

def calculate_height(r, g, b):
    avg = (r+g+b)/3
    return int(avg / 255 * 32 + 0)

x = 0
y = 0
hs = []

with open(map_ppm_path) as f:
    f.readline()
    f.readline()
    xy = f.readline().strip().split(" ")
    x = int(xy[0])
    y = int(xy[1])
    f.readline()
    for _ in range(x):
        for _ in range(y):
            r = int(f.readline().strip())
            g = int(f.readline().strip())
            b = int(f.readline().strip())
            h = calculate_height(r, g, b)
            hs.append(h)

with open(map_output_path, "w") as map_file:
    for _y in range(y):
        for _x in range(x):
            h = hs[_y * x + _x]
            for _z in range(h):
                t = 0
                if _z < h-4:
                    t = stone_block_id
                elif _z < h-1:
                    t = dirt_block_id
                else:
                    t = grass_block_id
                map_file.write("%s %s %s %s\n" % (
                    t,
                    _x - int(x/2),
                    int(y/2) - _y - 1,
                    _z,
                ))
